name: Run Javascript Extension Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run setup
    
    - name: Run unit tests
      run: npm run test:unit
    
    - name: Run integration tests
      run: npm run test:integration
    
    - name: Upload unit and integration test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-integration-test-results
        path: test-results/junit.xml
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-and-integration-tests
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run setup
    
    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
    
    - name: Upload E2E test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: test-results/junit.xml

  csp-tests:
    runs-on: ubuntu-latest
    needs: unit-and-integration-tests
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run setup
    
    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Run CSP tests
      run: npm run test:csp
      env:
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
    
    - name: Upload CSP test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: csp-test-results
        path: test-results/junit.xml

  publish-test-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    needs: [unit-and-integration-tests, e2e-tests, csp-tests]
    if: always()
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: artifacts/**/junit.xml
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: artifacts/coverage-report
        fail_ci_if_error: false